package com.chy.smdc.dao;

import com.chy.smdc.bean.Rolepermission;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface RolepermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbggenerated
     */
    int insert(Rolepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbggenerated
     */
    int insertSelective(Rolepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbggenerated
     */
    Rolepermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Rolepermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolepermission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Rolepermission record);
}