package com.chy.smdc.bean;

public class Rolepermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolepermission.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolepermission.roleid
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolepermission.permisionid
     *
     * @mbggenerated
     */
    private Integer permisionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolepermission.id
     *
     * @return the value of rolepermission.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolepermission.id
     *
     * @param id the value for rolepermission.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolepermission.roleid
     *
     * @return the value of rolepermission.roleid
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolepermission.roleid
     *
     * @param roleid the value for rolepermission.roleid
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolepermission.permisionid
     *
     * @return the value of rolepermission.permisionid
     *
     * @mbggenerated
     */
    public Integer getPermisionid() {
        return permisionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolepermission.permisionid
     *
     * @param permisionid the value for rolepermission.permisionid
     *
     * @mbggenerated
     */
    public void setPermisionid(Integer permisionid) {
        this.permisionid = permisionid;
    }
}